// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://swthriqtqsafyjbccnkn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN3dGhyaXF0cXNhZnlqYmNjbmtuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc5MTY3OTgsImV4cCI6MjA1MzQ5Mjc5OH0.GhZc81th5H53tV5atiwK6Iu-C9cdUYbaOazhIjJabZc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);